Repository huynamboz/e-commerce-server, pull requests merged in 2023-05, with the labels that each got.

#45 chore: Phuc - refactor code
  src/Core/Api/V1/Controllers/authController.cs
  src/Core/App.cs
  src/Core/Config/AppBundle.cs
  src/Core/Database/DatabaseConnect.cs
  src/Core/Env/ENV.cs
  src/Core/Env/EnvEnum.cs
  src/Core/Modules/Auth/Dto/ResetPasswordDto.cs
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Auth/Service/CryptoService.cs
  src/Core/Modules/Auth/Service/SendGridService.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Report/Service/ReportService.cs
  src/Core/Modules/Review/ReviewRepository.cs
  src/Core/Modules/Review/Service/ReviewService.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Utils/Optional.cs
  src/Packages/Swagger/Core/SwaggerBuilder.cs
Labels: bug, chore

#46 feat:Long - search products
  e-commerce-server.sln
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductService.cs
Labels: chore, feature

#49 feat: Long - get all categories
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Modules/Location/LocationRepository.cs
  src/Core/Modules/Location/Service/LocationService.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Report/ReportRepository.cs
  src/Core/Modules/Report/Service/ReportService.cs
  src/Core/Modules/Review/ReviewRepository.cs
  src/Core/Modules/Review/Service/ReviewService.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
Labels: chore, feature

#54 hotfix: Phuc - get user's info from favorite product
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/User/Service/UserService.cs
Labels: bug

#63 enhance: Phuc - allow uploading webp files
  src/Core/Config/FileConfig.cs
Labels: enhancement

#65 feat/Long - get all products by user
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Api/V1/Controllers/usersController.cs
Labels: feature

#58 hotfix: Nam - fix get favorite product's thumbnails
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductService.cs
Labels: bug

#71 hotfix: Phuc - cannot upload .webp images
  src/Core/Config/FileConfig.cs
  src/Core/Modules/Media/Service/MediaService.cs
Labels: bug
