Repository huynamboz/e-commerce-server, pull requests merged in 2023-04, with the labels that each got.

#8 Chore: Phuc - build base code
  .gitignore
  App.cs
  Program.cs
  e-commerce-server.csproj
  src/Core/Api/V1/Controllers/User/userController.cs
  src/Core/Config/AppBundle.cs
  src/Core/Config/SwaggerConfig.cs
  src/Core/Database/Data/MyDbContext.cs
  src/Core/Database/DatabaseConnect.cs
  src/Core/Env/ENV.cs
  src/Core/Modules/Auth/Dto/LoginDto.cs
  src/Packages/Auth/Core/JwtBearerOption.cs
  src/Packages/Extensions/Cors/CorsOption.cs
  src/Packages/HttpExceptions/UnAuthorizedException.cs
  src/Packages/Swagger/Core/SwaggerBuilder.cs
  src/Packages/Swagger/Filter/AuthorizeCheckOperationFilter.cs
Labels: chore

#7 enhance: Long - verify password when login
  src/Core/Env/ENV.cs
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Auth/Service/BCryptService.cs
Labels: enhancement

#10 chore: Phuc - update readme
  README.md
Labels: chore

#11 enhance: Phuc - product API naming convention
  src/Core/Api/V1/Controllers/Product/productsController.cs
  src/Core/Database/Data/MyDbContext.cs
  src/Core/Env/ENV.cs
  src/Core/Modules/Auth/Service/AuthEnum.cs
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Product/Service/ProductEnum.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Product/productRespository.cs
  src/Core/Modules/User/UserRepository.cs
Labels: enhancement

#12 hotfix: Nam - fix migration
  e-commerce-server.csproj.user
  src/Core/Database/Migrations/20230406185739_create_product_statuses_table.cs
Labels: bug

#13 feat: Phuc - view and delete my product
  src/Core/Api/V1/Controllers/Product/productsController.cs
  src/Core/Modules/Product/Service/ProductEnum.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Product/productRespository.cs
Labels: feature

#15 feat: Long - edit user information
  src/Core/Api/V1/Controllers/User/userController.cs
  src/Core/Modules/Auth/Service/AuthEnum.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/User/Dto/UpdateUserDto.cs
  src/Core/Modules/User/Service/UserEnum.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
Labels: feature

#16 feat: Phuc - upload images
  .env.example
  e-commerce-server.csproj
  src/Core/Api/V1/Controllers/Product/productsController.cs
  src/Core/App.cs
  src/Core/Config/AppBundle.cs
  src/Core/Config/FileConfig.cs
  src/Core/Config/SwaggerConfig.cs
  src/Core/Database/Data/MyDbContext.cs
  src/Core/Database/DatabaseConnect.cs
  src/Core/Env/ENV.cs
  src/Core/Modules/Media/Interceptor/MediaInterceptor.cs
  src/Core/Modules/Media/MediaHandler.cs
  src/Core/Modules/Media/Service/FileSystemService.cs
  src/Core/Modules/Media/Service/MediaEnum.cs
  src/Core/Modules/Media/Service/MediaService.cs
  src/Core/Modules/Product/Dto/AddProductDto.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Product/productRespository.cs
  src/Packages/Files/Core/FilesOption.cs
  src/Packages/Swagger/Core/SwaggerBuilder.cs
Labels: feature

#18 feat: Long - view user's profile
  src/Core/Api/V1/Controllers/User/userController.cs
  src/Core/Modules/User/Dto/UserDto.cs
  src/Core/Modules/User/Service/UserService.cs
Labels: feature

#19 enhance: Phuc - add interceptors
  src/Core/Modules/Auth/Dto/LoginDto.cs
  src/Core/Modules/Auth/Dto/RegisterDto.cs
  src/Core/Modules/Media/MediaHandler.cs
  src/Core/Modules/Product/Dto/ProductDto.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/User/Dto/UpdateUserDto.cs
  src/Core/Modules/User/Dto/UserDto.cs
  src/Core/Uploads/Media/README.md
Labels: enhancement

#17 feat: Phuc - user avatar
  src/Core/Api/V1/Controllers/Product/productsController.cs
  src/Core/Api/V1/Controllers/User/userController.cs
  src/Core/Modules/Media/Service/FileSystemService.cs
  src/Core/Modules/User/Dto/UpdateUserDto.cs
  src/Core/Modules/User/Service/UserService.cs
Labels: feature

#22 chore: Phuc - update readme
  .env.example
  README.md
  src/Core/Database/DatabaseConnect.cs
  src/Core/Database/MyDbContext.cs
  src/Core/Env/ENV.cs
  src/Core/Modules/Auth/Service/MailContent.cs
Labels: chore

#24 chore: Phuc - refactor repositories
  src/Core/Api/V1/Controllers/userController.cs
  src/Core/Config/FileConfig.cs
  src/Core/Database/Data/FavoriteData.cs
  src/Core/Database/Data/ProductData.cs
  src/Core/Database/Data/ProductStatusData.cs
  src/Core/Database/Data/ThumbnailData.cs
  src/Core/Database/MyDbContext.cs
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Auth/Service/JwtService.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Product/productRespository.cs
  src/Core/Modules/User/Service/UserEnum.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
  src/Packages/Extensions/Cors/CorsOption.cs
  src/Packages/Files/Core/FilesOption.cs
Labels: chore, feature

#25 feat: Long - get all users
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Api/V1/Controllers/userController.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
Labels: feature

#27 feat: Phuc - upload images endpoint
  src/Core/Api/V1/Controllers/authController.cs
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Api/V1/Controllers/uploadController.cs
  src/Core/Api/V1/Controllers/userController.cs
  src/Core/Database/Data/ProductData.cs
  src/Core/Database/MyDbContext.cs
  src/Core/Modules/Media/MediaHandler.cs
  src/Core/Modules/Media/Service/MediaService.cs
  src/Core/Modules/Product/Dto/AddProductDto.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/User/Dto/UpdateUserDto.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
  src/Packages/HttpExceptions/BadRequestException.cs
  src/Packages/HttpExceptions/ForbiddenException.cs
Labels: chore, feature

#30 hotfix: Phuc - rename user controller
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Api/V1/Controllers/usersController.cs
Labels: bug

#32 Long - delete product
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductEnum.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
Labels: feature

#42 chore: Nam - update admin api naming convention
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Modules/User/UserRepository.cs
Labels: chore

#38 feat: Long - delete review
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Modules/Review/ReviewRepository.cs
  src/Core/Modules/Review/Service/ReviewEnum.cs
  src/Core/Modules/Review/Service/ReviewService.cs
Labels: feature

#43 feat: Long - get all reports by admin
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Modules/Report/ReportRepository.cs
  src/Core/Modules/Report/Service/ReportEnum.cs
  src/Core/Modules/Report/Service/ReportService.cs
Labels: feature
