Repository huynamboz/e-commerce-server, pull requests merged in 2023-06, with the labels that each got.

#76 chore: Phuc - fix random string generator
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Auth/Service/CryptoService.cs
  src/Core/Modules/Auth/Service/MailContent.cs
Labels: bug

#75 feat: Long - get all products by category
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductEnum.cs
  src/Core/Modules/Product/Service/ProductService.cs
Labels: feature

#48 feat: Long - search and filter product
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Modules/Product/ProductRespository.cs
  src/Core/Modules/Product/Service/ProductService.cs
Labels: feature

#78 feat: Phuc - add role guard
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Common/Enum/RoleEnum.cs
  src/Core/Config/SwaggerConfig.cs
  src/Core/Modules/Auth/Service/JwtService.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Report/Service/ReportService.cs
  src/Core/Modules/User/Service/UserService.cs
  src/Core/Modules/User/UserRepository.cs
Labels: feature

#80 chore: Phuc - add role_id to access token
  src/Core/Modules/Auth/Service/JwtService.cs
Labels: chore

#79 chore: Phuc - refactor status code
  src/Core/Api/V1/Controllers/authController.cs
  src/Core/Api/V1/Controllers/productsController.cs
  src/Core/Api/V1/Controllers/uploadController.cs
  src/Core/Env/ENV.cs
  src/Core/Modules/Auth/Service/AuthService.cs
  src/Core/Modules/Media/Service/MediaService.cs
  src/Core/Modules/Product/Service/ProductService.cs
  src/Core/Modules/Report/Service/ReportService.cs
  src/Core/Modules/User/Service/UserService.cs
Labels: chore

#85 feat:Long - unban users
  src/Core/Api/V1/Controllers/adminController.cs
  src/Core/Modules/User/Service/UserEnum.cs
  src/Core/Modules/User/Service/UserService.cs
Labels: feature
